name: WhatsApp Notification

on:
  push:
    branches:
      - "*"

jobs:
  send-whatsapp-message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install twilio

      - name: Send WhatsApp message
        run: |
          echo "const accountSid = process.env.TWILIO_ACCOUNT_SID;" > script.js
          echo "const authToken = process.env.TWILIO_AUTH_TOKEN;" >> script.js
          echo "const client = require('twilio')(accountSid, authToken);" >> script.js
          echo "console.log(process.env.TWILIO_ACCOUNT_SID, process.env.TWILIO_AUTH_TOKEN, process.env.TWILIO_PHONE_NUMBER);" >> script.js
          echo "client.messages.create({" >> script.js
          echo "  body: 'Repository updated!'," >> script.js
          echo "  from: 'whatsapp:' + process.env.TWILIO_PHONE_NUMBER," >> script.js
          echo "  to: 'whatsapp:+919173066857'" >> script.js
          echo "}).then(message => console.log('WhatsApp message sent:', message.sid));" >> script.js
          
          node script.js
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          TWILIO_PHONE_NUMBER: ${{ secrets.TWILIO_PHONE_NUMBER }}
